#+TITLE: 
#+AUTHOR: 
#+DATE: 

#+STARTUP: inlineimages
#+LANGUAGE: ca
#+DESCRIPTION: 
#+PANDOC_OPTIONS: standalone:t latex-engine:xelatex
#+BIBLIOGRAPHY: ./index.bib
#+ARCHIVE: %s_done::

* 0. FUNCIONS EXECUTIVES             

Les funcions executives són activitats mentals complexes, necessàries per planificar, organitzar, guiar, revisar, regularitzar i avaluar el comportament necessari per adaptar-se eficaçment a l'entorn i per assolir metes (Bauermeister, 2008).

** 1. Organització

- Definició: Habilitat que permet als xiquets/es mantenir la tractectoria a seguir tant física com a mental per arribar a un objectiu.
- Manifestació: Els xiquets amb habilitats d'organització febles poden perdre fàcilment el rumb del seu pensament, igual que objectes o tasques.
- Avaluació:

** 2. Presa de decions

- Definició: Habilitat que permet als infants fer una elecció entre diverses alternatives en funció de les nostres necessitats, sospesant els resultats i les conseqüències de totes les opcions.
- Manifestació: Els nens amb habilitats febles d'organització manifesten dificultats a l'hora d'escollir.
- Avaluació:

** 3. Planificació i priorització

- Definició: Aquesta habilitat ajuda els nens a decidir sobre un objectiu i un pla per dur-ho a terme.
- Manifestació: Els nens amb aquestes habilitats febles no poden diferenciar quines parts d‟un projecte són més importants.
- Avaluació:

** 4. Control d'impulsos

- Definició: Habilitat que ajuda els nens a pensar abans dactuar.
- Manifestació: Respostes impulsives sense pensar, per la qual cosa poden provocar conseqüències no desitjades tant en avaluació del coneixement com en accions.
- Avaluació:

** 5. Inhibició

- Definició: Habilitat per ignorar els impulsos o la informació irrellevant tant interna com externa quan estem fent una tasca.
- Manifestació: Els nens que tenen feble aquesta habilitat no es distreuen fàcilment amb informació no rellevant.
- Avaluació:

** 6. Autocontrol

- Definició: Habilitat que permet avaluar als nens el seu impacte al món.
- Manifestació: Els nens amb debilitats d'autocontrol poden presentar problemes amb les crítiques.
- Avaluació:

** 7. Control emocional

- Definició: Habilitat que ajuda els nens a mantenir els seus sentiments sota control.
- Manifestació: Els nens amb control emocional baix sovint reaccionen de forma exagerada. Poden tenir dificultats per enfrontar la crítica i la reorganització quan va malament.
- Avaluació:

** 8. Iniciació de la tasca

- Definició: És l'habilitat que ajuda els infants a iniciar tasques necessàries per assolir els seus objectius.
- Manifestació: Els nens que tenen feble aquesta habilitat no saben per on començar, per la qual cosa trigaran més a completar les seves tasques.
- Avaluació:

** 9. Pensament flexible

- Definició: Habilitat que permet adaptar-se a allò inesperat.
- Manifestació: Els nens amb pensament rígid no s'adapten als canvis encara que els afectin.
- Avaluació:

** 10. Raonament

- Definició: Aquesta habilitat que permet resoldre problemes de diversa índole, de manera conscient, establint relacions causals entre ells.
- Manifestació: Els nens amb aquestes habilitats febles no són capaços didentificar la informació significativa i establir vincles adequats per resoldre problemes.
- Avaluació:

** 11. Memòria de treball

- Definició: Habilitat que ajuda a mantenir la informació clau a la ment.
- Manifestació: Els nens amb dèficits en aquesta habilitat presenten dificultats per recordar dades.
- Avaluació:

** 12. Estimació temporal

- Definició: Habilitat que permet als nens calcular aproximadament el pas del temps i la durada d'un succés o activitat.
- Manifestació: Els nens amb habilitats d'estimació temporal febles tenen dificultats per valorar la durada de les seves tasques.
- Avaluació:
